MainArea/urls.py
# pages/urls.py
from django.urls import path , include, re_path
from MainArea import views
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView
from django.conf import settings
from .views import contact_form , ContactFormView , validate_username, SignUpView



app_name = 'main'

urlpatterns = [
#    path('dashboard/', views.home_page_view, name='home'),
    path("", views.UserDashboard, name="dashboard"),
    path('save_url/', views.UserDashboard, name='save_url'),
    path("register/", views.register, name="register"),
    path("logout", views.logout_request, name="logout"),
    path("login", views.login_request, name="login"),
    path('contact-form/', views.ContactFormView.as_view(), name='contact_form'),
    path("favicon.ico",RedirectView.as_view(url=staticfiles_storage.url("favicon.ico")),),
    # https://djangocentral.com/django-ajax-with-jquery/
    #########Making AJAX GET requests with Django and JQuery##########
    path('signup', SignUpView.as_view(), name='signup'),
    path('validate_username', validate_username, name='validate_username'),
    ###################
    ]

ProxyChecker/urls.py
# pages/urls.py
from ProxyChecker import views
from django.urls import path,re_path
#from .views import ajax_view
app_name = 'ProxyChecker'




urlpatterns = [
    path("", views.ProxyChecker, name="PChecker"),
    re_path(r'upload/csv/$', views.upload_csv, name='upload_csv'),
    path('contact-form/', views.URL_String_Upload.as_view(), name='contact_form'),
    #path('save_url/', views.URL_String_Upload.as_view(), name='save_url'),
    path('ajax/', views.ajax_view, name="ajax"), # https://engineertodeveloper.com/how-to-use-ajax-with-django/
]

VrahProxyStar/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('MainArea.urls')),
    path('', include('ProxyChecker.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ProxyChecker/forms.py
from django import forms
from .models import ProxyStringUrl



class InputCsvForm(forms.Form):
    #FileUpload = forms.FileUpload()
    Textfield = forms.CharField(widget=forms.Textarea)

class UrlStringFormView(forms.ModelForm):
    class Meta:
        model = ProxyStringUrl
        #fields = '__all__'
        fields = ['urlstring']

ProxyChecker/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from . import models
from django.contrib.auth.models import User
import logging
from django.contrib import messages
from django.views.generic.edit import FormView
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy

from .src.checker import checkPROXY_DB, FarmProxysOS
from .src.ismyipbad import IsMyIpBad

from .forms import InputCsvForm, UrlStringFormView
# parts
# - show the current user geolocation in the dashboard
# - get Longtitude, Altitude and City from the Proxys

# https://medium.com/@arrosid/get-visitor-location-using-geoip2-in-django-32ad3d417115

from django.contrib.gis.geoip2 import GeoIP2
from pprint import pprint
#g = GeoIP2()
#result = g.city('213.136.89.190')
#pprint(result)




""" HELPS
https://www.techiediaries.com/resetting-django-migrations/
"""

def ProxyChecker(request):
    if request.method == 'GET':
        form = InputCsvForm()
    else:
        # A POST request: Handle Form Upload
        form = InputCsvForm(request.POST)  # Bind data from request.POST into a PostForm
        # If data is valid, proceeds to create a new post and redirect the user
        if form.is_valid():
            # FileUpload = forms.FileUpload()
            Textfield = form.cleaned_data['Textfield']
            # save to db
            user = User.objects.get(id=1) #TODO:: Die Proxy müssen immer zu dem eingellogten User eingetragen werden
            proxy = models.UserProxy.objects.create(user=user, protokol="Socks5", country=Textfield)
            proxy.save()
            #print(proxy.protokol)
            # return HttpResponseRedirect(reverse('post_detail',kwargs={'post_id': post.id}))

    form = {}
    form['form'] = InputCsvForm()
    return render(request, "ProxyChecker/Pchecker.html", form)



class URL_String_Upload(FormView):
    template_name = 'userDashboard/Dashboard.html'
    form_class = UrlStringFormView

    def form_valid(self, form):
        """
        If the form is valid return HTTP 200 status
        code along with name of the user
        """
        name = form.cleaned_data['name']
        form.save()
        return JsonResponse({"name": name}, status=200)

    def form_invalid(self, form):
        """
        If the form is invalid return status 400
        with the errors.
        """
        errors = form.errors.as_json()
        return JsonResponse({"errors": errors}, status=400)



def upload_csv(request):
    """
    https://pythoncircle.com/post/30/how-to-upload-and-process-the-csv-file-in-django/
    """
    if request.user.is_anonymous:
        anoymous = 2
        print(request.user.id,"\n\n\n")
        user = User.objects.get(pk=anoymous)
        data = {}
        if "GET" == request.method:
            return render(request, "ProxyChecker/Pchecker.html", data)
        # if not GET, then proceed
        try:
            csv_file = request.FILES["csv_file"]
            if not csv_file.name.endswith('.csv'):
                messages.error(request, 'File is not CSV type')
                return HttpResponseRedirect(reverse("ProxyChecker:PChecker"))
            # if file is too large, return
            if csv_file.multiple_chunks():
                messages.error(request, "Uploaded file is too big (%.2f MB)." % (csv_file.size / (1000 * 1000),))
                return HttpResponseRedirect(reverse("ProxyChecker:PChecker"))

                # loop over the lines and save them in db. If error , store as string and then display
            file_data = csv_file.read().decode("utf-8")
            lines = file_data.split("\n")
            for line in lines:
                    fields = line.split(":")
                    data_dict = {}
                    data_dict["ipaddress"] = fields[0]
                    data_dict["port"] = fields[1]
                    #data_dict["First name"] = fields[2]
                    #data_dict["Last name"] = fields[3]
                    #print( "\n" ,str(data_dict), "\n")
                    try:
                        proxy = models.UserProxy.objects.create(user=user,
                                                                ipAdress=data_dict['ipaddress'],
                                                                port=data_dict['port'])
                        proxy.save()
                        #form = EventsForm(data_dict) # <-----------------------
                        #if form.is_valid():
                        #    form.save()
                        #else:
                        #    logging.getLogger("error_logger").error(form.errors.as_json())
                    except Exception as e:
                        logging.getLogger("error_logger").error(repr(e))
                        pass
        except Exception as e:
                logging.getLogger("error_logger").error("Unable to upload file. " + repr(e))
                messages.error(request, "Unable to upload file. " + repr(e))
    else:

        print(request.user.id,"\n\n\n")
        user = User.objects.get(pk=request.user.id)
        data = {}
        if "GET" == request.method:
            return render(request, "ProxyChecker/Pchecker.html", data)
        # if not GET, then proceed
        try:
            csv_file = request.FILES["csv_file"]
            if not csv_file.name.endswith('.csv'):
                messages.error(request, 'File is not CSV type')
                return HttpResponseRedirect(reverse("ProxyChecker:PChecker"))
            # if file is too large, return
            if csv_file.multiple_chunks():
                messages.error(request, "Uploaded file is too big (%.2f MB)." % (csv_file.size / (1000 * 1000),))
                return HttpResponseRedirect(reverse("ProxyChecker:PChecker"))

                # loop over the lines and save them in db. If error , store as string and then display
            file_data = csv_file.read().decode("utf-8")
            lines = file_data.split("\n")
            for line in lines:
                    fields = line.split(":")
                    data_dict = {}
                    data_dict["ipaddress"] = fields[0]
                    data_dict["port"] = fields[1]
                    #data_dict["First name"] = fields[2]
                    #data_dict["Last name"] = fields[3]
                    #print( "\n" ,str(data_dict), "\n")
                    try:
                        proxy = models.UserProxy.objects.create(user=user,
                                                                ipAdress=data_dict['ipaddress'],
                                                                port=data_dict['port'])
                        proxy.save()
                        #form = EventsForm(data_dict) # <-----------------------
                        #if form.is_valid():
                        #    form.save()
                        #else:
                        #    logging.getLogger("error_logger").error(form.errors.as_json())
                    except Exception as e:
                        logging.getLogger("error_logger").error(repr(e))
                        pass
        except Exception as e:
                logging.getLogger("error_logger").error("Unable to upload file. " + repr(e))
                messages.error(request, "Unable to upload file. " + repr(e))


    # def background_process():
    #     print("\033[1;34m"+"process started")
    #     checkPROXY_DB(request)
    #     #FarmProxysOS()
    #     print("\033[1;34m"+"process finished")
    #def index(request):
    #    import threading
    #    t = threading.Thread(target=background_process, args=(), kwargs={})
    #    t.setDaemon(True)
    #    t.start()
    #    return HttpResponse("main thread content")

    # import threading
    # t = threading.Thread(target=background_process, args=(), kwargs={})
    # t.setDaemon(True)
    # t.start()

    return HttpResponseRedirect(reverse("main:dashboard"))

def ajax_view(request):
    if request.method == "POST":
        print(request.POST)
        data = {
            "msg": "Data has been POSTED!",
        }
        return JsonResponse(data)
    else:
        data = {
            "msg": "It worked!!",
        }
        return JsonResponse(data)


def BrowserLocation(request):


    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')

    #result = IsMyIpBad(ip)

    for i in request:
        print(i)

    device_type = ""
    browser_type = ""
    browser_version = ""
    os_type = ""
    os_version = ""
    if request.user_agent.is_mobile:
        device_type = "Mobile"
    if request.user_agent.is_tablet:
        device_type = "Tablet"
    if request.user_agent.is_pc:
        device_type = "PC"

    browser_type = request.user_agent.browser.family
    browser_version = request.user_agent.browser.version_string
    os_type = request.user_agent.os.family
    os_version = request.user_agent.os.version_string

    g = GeoIP2()
    location = g.city(ip)
    location_country = location["country_name"]
    location_city = location["city"]
    context = {"ip": ip,
                "device_type": device_type,
                "browser_type": browser_type,
                "browser_version": browser_version,
                "os_type":os_type,
                "os_version":os_version,
                "location_country": location_country,
                "location_city": location_city}
    return context

templates/ProxyChecker/Pchecker.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
  <link rel="stylesheet" href="{% static 'welcome/css/theme.css' %}" type="text/css">
</head>

<body >
  <nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <div class="container"> <a class="navbar-brand" href="#">
        <i class="fa d-inline fa-lg fa-stop-circle"></i>
        <b> Vrah-Proxy-Star</b>
      </a> <button class="navbar-toggler navbar-toggler-right border-0" type="button" data-toggle="collapse" data-target="#navbar10">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar10">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item"> <a class="nav-link" href="#">Features</a> </li>
          <li class="nav-item"> <a class="nav-link" href="#">Pricing</a> </li>
          <li class="nav-item"> <a class="nav-link" href="#">About</a> </li>
          <li class="nav-item"> <a class="nav-link" href="#">FAQ</a> </li>
          {% if user.is_authenticated %}
          <li class="nav-item"> <a class="nav-link" href="#">Hi {{ user.username }}!</a> </li>
          <li class="nav-item"><a class="nav-link" href="{% url 'main:logout' %}">Log Out</a></li>
{% else %}
<li class="nav-item"> <a class="nav-link" href="#">You are not logged in</a> </li>
  <li class="nav-item"><a class="nav-link" href="{% url 'main:login' %}">Log In</a></li>
{% endif %}
      </div>
    </div>
  </nav>
  <div class="py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <!--/*   Section für Template entwicklung */ -->

          <form action = "" method = "post">
            <div class="form-group">
              <div class="col-md-6 form-horizontal">
              {% csrf_token %}

              {{form }}
              <input type="submit" value="Submit">
            </div>
          </div>

          </form>

    <!--/*   Section für Template entwicklung FORM 2*/ -->


          <form action="{% url "ProxyChecker:upload_csv" %}" method="POST" enctype="multipart/form-data" class="form-horizontal">
          {% csrf_token %}
          <div class="form-group">
              <label for="name" class="col-md-3 col-sm-3 col-xs-12 control-label">File: </label>
              <div class="col-md-6">
                  <input type="file" name="csv_file" id="csv_file" required="True" class="form-control">
              </div>
          </div>
          <div class="form-group">
              <div class="col-md-3 col-sm-3 col-xs-12 col-md-offset-3" style="margin-bottom:10px;">
                   <button class="btn btn-primary"> <span class="glyphicon glyphicon-upload" style="margin-right:5px;"></span>Upload </button>
              </div>
          </div>
          </form>



          <!--  Section für Template entwicklung -->
        </div>
      </div>
      <div class="row">
        <div class="col-md-4">
        </div>
        <div class="col-md-4"></div>
      </div>
    </div>
  </div>
  <div class="py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-12"></div>
      </div>
    </div>
  </div>
  <div class="py-3">
    <div class="container">
      <div class="row">
        <div class="col-lg-3 col-6 p-3">
          <h5> <b>Main</b> </h5>
          <ul class="list-unstyled">
            <li> <a href="#">Home</a> </li>
            <li> <a href="#">Features</a> </li>
            <li> <a href="#">Pricing</a><a href="#">Pricing</a> </li>
          </ul>
        </div>
        <div class="col-lg-3 col-6 p-3">
          <h5> <b>Others</b> </h5>
          <ul class="list-unstyled">
            <li> <a href="#">FAQ</a> </li>
            <li> <a href="#">Resources</a> </li>
            <li> <a href="#">Impressum</a> </li>
          </ul>
        </div>
        <div class="col-lg-3 col-md-6 p-3">
          <h5> <b>About</b> </h5>
          <p class="mb-0"> I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls.</p>
        </div>
        <div class="col-lg-3 col-md-6 p-3">
          <h5> <b>Follow us</b> </h5>
          <div class="row">
            <div class="col-md-12 d-flex align-items-center justify-content-between my-2"> <a href="#">
                <i class="d-block fa fa-facebook-official text-muted fa-lg mr-2"></i>
              </a> <a href="#">
                <i class="d-block fa fa-instagram text-muted fa-lg mx-2"></i>
              </a> <a href="#">
                <i class="d-block fa fa-google-plus-official text-muted fa-lg mx-2"></i>
              </a> <a href="#">
                <i class="d-block fa fa-pinterest-p text-muted fa-lg mx-2"></i>
              </a> <a href="#">
                <i class="d-block fa fa-reddit text-muted fa-lg mx-2"></i>
              </a> <a href="#">
                <i class="d-block fa fa-twitter text-muted fa-lg ml-2"></i>
              </a> </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous" style=""></script>
</body>

</html>