MainArea/urls.py
# pages/urls.py
from django.urls import path , include, re_path
from MainArea import views
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView
from django.conf import settings
from .views import contact_form , ContactFormView , validate_username, SignUpView



app_name = 'main'

urlpatterns = [
#    path('dashboard/', views.home_page_view, name='home'),
    path("", views.UserDashboard, name="dashboard"),
    path('save_url/', views.UserDashboard, name='save_url'),
    path("register/", views.register, name="register"),
    path("logout", views.logout_request, name="logout"),
    path("login", views.login_request, name="login"),
    path('contact-form/', views.ContactFormView.as_view(), name='contact_form'),
    path("favicon.ico",RedirectView.as_view(url=staticfiles_storage.url("favicon.ico")),),
    # https://djangocentral.com/django-ajax-with-jquery/
    #########Making AJAX GET requests with Django and JQuery##########
    path('signup', SignUpView.as_view(), name='signup'),
    path('validate_username', validate_username, name='validate_username'),
    ###################
    ]

VrahProxyStar/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('MainArea.urls')),
    path('', include('ProxyChecker.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/contacts/contacts.html
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contact us</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

</head>

<body>
    <div class="container mt-5 w-50">
        <form id="contactForm" method="POST">
            {% csrf_token %}
            {{ form|crispy  }}
            <input type="submit" name="contact-submit" class="btn btn-success btn-lg" />
        </form>
    </div>
    {% block javascript %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <script>
        $(document).ready(function () {
            // catch the form's submit event
            $('#contactForm').submit(function () {
                // create an AJAX call
                $.ajax({
                    data: $(this).serialize(), // get the form data
                    type: $(this).attr('method'), // GET or POST
                    url: "{% url 'main:contact_form' %}",
                    // on success
                    success: function (response) {
                        alert("Thankyou for reaching us out " + response.name);
                    },
                    // on error
                    error: function (response) {
                        // alert the error if any error occured
                        alert(response.responseJSON.errors);
                        console.log(response.responseJSON.errors)
                    }
                });
                return false;
            });
        })
    </script>
    {% endblock javascript %}
</body>

</html>